// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyExchange.Data;

#nullable disable

namespace MyExchange.Data.Migrations
{
    [DbContext(typeof(MyExchangeContext))]
    partial class MyExchangeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyExchange.Data.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("BankId");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.BankCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("Cvv")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<long>("Number")
                        .HasMaxLength(16)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TerminalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("BankCardId");

                    b.HasIndex("BankId");

                    b.HasIndex("WalletId");

                    b.ToTable("BankCards");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("decimal(38,19)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .HasName("PromoCodeId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("PromoCode");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("PhoneNumber")
                        .HasMaxLength(12)
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalClosedMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCurrentCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCurrentMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEnrolment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWithdrawl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WalletType")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("WalletId");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.WalletPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("ClosePrice")
                        .HasColumnType("decimal(38,19)");

                    b.Property<decimal?>("ClosedMargin")
                        .HasColumnType("decimal(38,19)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentMargin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(38,19)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(38,19)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(38,19)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("WalletPositionId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletPositions");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.WalletsPromoCodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PromoCodeId")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("WalletsPromoCodesId");

                    b.HasIndex("PromoCodeId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletsPromoCodes");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.BankCard", b =>
                {
                    b.HasOne("MyExchange.Data.Entities.Bank", "Bank")
                        .WithMany("BankCards")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyExchange.Data.Entities.Wallet", "Wallet")
                        .WithMany("BankCards")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.PromoCode", b =>
                {
                    b.HasOne("MyExchange.Data.Entities.Currency", "Currency")
                        .WithMany("PromoCodes")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.Wallet", b =>
                {
                    b.HasOne("MyExchange.Data.Entities.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.WalletPosition", b =>
                {
                    b.HasOne("MyExchange.Data.Entities.Currency", "Currency")
                        .WithMany("WalletPositions")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyExchange.Data.Entities.Wallet", "Wallet")
                        .WithMany("WalletPositions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.WalletsPromoCodes", b =>
                {
                    b.HasOne("MyExchange.Data.Entities.PromoCode", "PromoCode")
                        .WithMany("WalletsPromoCodes")
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyExchange.Data.Entities.Wallet", "Wallet")
                        .WithMany("WalletsPromoCodes")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromoCode");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.Bank", b =>
                {
                    b.Navigation("BankCards");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.Currency", b =>
                {
                    b.Navigation("PromoCodes");

                    b.Navigation("WalletPositions");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.PromoCode", b =>
                {
                    b.Navigation("WalletsPromoCodes");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.User", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("MyExchange.Data.Entities.Wallet", b =>
                {
                    b.Navigation("BankCards");

                    b.Navigation("WalletPositions");

                    b.Navigation("WalletsPromoCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
